import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import PageHeader from '../components/PageHeader';
import Wallet from '../components/Wallet';
import SwitchChain from '../components/SwitchChains';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <PageHeader />
      <main className={styles.main}>
        <Wallet />
        <SwitchChain />
      </main>
        
    </div>
  );
};

export default Home;
